import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { GridVerticalGuides } from "@/components/grid";
import { ThemeToggle } from "@/components/theme/theme-toggle";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider, ThemeScript } from "@/providers/theme";
import { cn } from "@/utils/cn";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable
      )}
    >
      <head>
        <ThemeScript />
      </head>
      <body className="relative min-h-full w-full overflow-x-hidden flex flex-col">
        <ThemeProvider>
          <TooltipProvider>
            <GridVerticalGuides />
            <div className="relative z-10 flex min-h-full flex-1 flex-col">
              {children}
            </div>
            <ThemeToggle />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
